//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAI.GeneradorPDF.facturas.usuarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_configuration
    {
        public int idconfiugration { get; set; }
        public string CompanyDB { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ip { get; set; }
    }
}
