//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAI.GeneradorPDF.facturas.usuarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correlatives
    {
        public int id_Seq { get; set; }
        public Nullable<int> serie { get; set; }
        public string location_code { get; set; }
        public string cost_center { get; set; }
        public string company { get; set; }
        public string rentworks_code { get; set; }
    }
}
