//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAI.GeneradorPDF.facturas.usuarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hertz_ProjectsEntities : DbContext
    {
        public Hertz_ProjectsEntities()
            : base("name=Hertz_ProjectsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<api_configuration> api_configuration { get; set; }
        public virtual DbSet<correlatives> correlatives { get; set; }
        public virtual DbSet<ssai_users> ssai_users { get; set; }
        public virtual DbSet<locations> locations { get; set; }
    }
}
