//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAI.GeneradorPDF.facturas.usuarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssai_users
    {
        public int id_user { get; set; }
        public string rolecode { get; set; }
        public string locationcode { get; set; }
        public string codigoType { get; set; }
        public Nullable<int> id_vendedor { get; set; }
        public string employee_first_name { get; set; }
        public string employee_last_name { get; set; }
        public string user_SSAI { get; set; }
        public string password_SSAI { get; set; }
        public Nullable<bool> state { get; set; }
        public byte[] firma { get; set; }
    }
}
